{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-test",
    "version": "3.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.4"
          }
        },
        {
          "group": "org.awaitility",
          "module": "awaitility",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.12.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.10.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-3.5.6.jar",
          "url": "spring-boot-starter-test-3.5.6.jar",
          "size": 4791,
          "sha512": "2ded1ce2736325fb46bbb3b5c016505002137ea7869fe9ceec37f42701de722b53f2bef5bca0258b41daab630e49b7b10db3802f87df299bbf31ced7c37f7017",
          "sha256": "c39acd1f64c1e649511d96854f6c595562c0dd2af4aa121903f496827792d5de",
          "sha1": "a9d9c8bbd492d33c359a8d5b32a80396b2bc212f",
          "md5": "4a0671747e02661f5876801a4a800cdf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.4"
          }
        },
        {
          "group": "org.awaitility",
          "module": "awaitility",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.12.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.10.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-3.5.6.jar",
          "url": "spring-boot-starter-test-3.5.6.jar",
          "size": 4791,
          "sha512": "2ded1ce2736325fb46bbb3b5c016505002137ea7869fe9ceec37f42701de722b53f2bef5bca0258b41daab630e49b7b10db3802f87df299bbf31ced7c37f7017",
          "sha256": "c39acd1f64c1e649511d96854f6c595562c0dd2af4aa121903f496827792d5de",
          "sha1": "a9d9c8bbd492d33c359a8d5b32a80396b2bc212f",
          "md5": "4a0671747e02661f5876801a4a800cdf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-3.5.6-javadoc.jar",
          "url": "spring-boot-starter-test-3.5.6-javadoc.jar",
          "size": 4791,
          "sha512": "cad9d4333f22f4217b2a8275344bc5944bbc05c40c68f275713c65d514ffe73d08b62e1250ca9e7bee999e11dacce73b2ff55f6e755d41fde022213110fb8231",
          "sha256": "1a0fdbd4d60a53408868662c315a44c018ff80b4392ccdf89cbc3ee947721b9f",
          "sha1": "ba9117aa12505185e6f9d6bd3c4f5c0158031aa7",
          "md5": "371651a207ce33a8da2afa3627d86d07"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-3.5.6-sources.jar",
          "url": "spring-boot-starter-test-3.5.6-sources.jar",
          "size": 4791,
          "sha512": "cad9d4333f22f4217b2a8275344bc5944bbc05c40c68f275713c65d514ffe73d08b62e1250ca9e7bee999e11dacce73b2ff55f6e755d41fde022213110fb8231",
          "sha256": "1a0fdbd4d60a53408868662c315a44c018ff80b4392ccdf89cbc3ee947721b9f",
          "sha1": "ba9117aa12505185e6f9d6bd3c4f5c0158031aa7",
          "md5": "371651a207ce33a8da2afa3627d86d07"
        }
      ]
    }
  ]
}
