{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "6.2.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.2.11.jar",
          "url": "spring-webmvc-6.2.11.jar",
          "size": 1091817,
          "sha512": "e355a131e16e97783be60c193ae6d7b4a5a6ca80a25471e4c00e5b65c7e213032f431e8efd96c801153d73b606837ce79279b0f6893a9d13f42fada5d9764f20",
          "sha256": "c1949970b2702809fb85bafa1e3b3c6e68a8e69248e77cd77cde273fb24db139",
          "sha1": "3313fe95e06c1d3c94d00301cbed56ed1a9d2a86",
          "md5": "f8770223d9df23ae801dd9a9ccbb0ae6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.2.11.jar",
          "url": "spring-webmvc-6.2.11.jar",
          "size": 1091817,
          "sha512": "e355a131e16e97783be60c193ae6d7b4a5a6ca80a25471e4c00e5b65c7e213032f431e8efd96c801153d73b606837ce79279b0f6893a9d13f42fada5d9764f20",
          "sha256": "c1949970b2702809fb85bafa1e3b3c6e68a8e69248e77cd77cde273fb24db139",
          "sha1": "3313fe95e06c1d3c94d00301cbed56ed1a9d2a86",
          "md5": "f8770223d9df23ae801dd9a9ccbb0ae6"
        }
      ]
    }
  ]
}
